# -*- encoding: utf-8 -*-
"""
系统常量池.

@Time    :   2024/05/14 11:07:06
@Author  :   creativor 
@Version :   1.0
"""


class Tokens:
    """Token常量池"""

    SUBSCRIBES_HELP = "要定阅的MQTT主题列表,用逗号分隔"
    SUBSCRIBES = "订阅列表"
    DETECTION_SOURCE = "检测来源"
    THREAD_NAME = "线程名称"
    MODEL_NAME = "模型名称"
    RTSP_URL = "RTSP视频流URL"
    SLEEP_TIME = "检测间隔(秒)"
    CALLBACK_URL = "回调URL地址"
    RUNNING_STATUS = "运行状态"
    STREAMS = "视频流列表"
    CAMERA_SN = "摄像头编号"


# AG-GRID的原始英文语言包
AG_GRID_LOCALE_EN = {
    # Set Filter
    "selectAll": "(Select All)",
    "selectAllSearchResults": "(Select All Search Results)",
    "addCurrentSelectionToFilter": "Add current selection to filter",
    "searchOoo": "Search...",
    "blanks": "(Blanks)",
    "noMatches": "No matches",
    # Number Filter & Text Filter
    "filterOoo": "Filter...",
    "equals": "Equals",
    "notEqual": "Does not equal",
    "blank": "Blank",
    "notBlank": "Not blank",
    "empty": "Choose one",
    # Number Filter
    "lessThan": "Less than",
    "greaterThan": "Greater than",
    "lessThanOrEqual": "Less than or equal to",
    "greaterThanOrEqual": "Greater than or equal to",
    "inRange": "Between",
    "inRangeStart": "From",
    "inRangeEnd": "To",
    # Text Filter
    "contains": "Contains",
    "notContains": "Does not contain",
    "startsWith": "Begins with",
    "endsWith": "Ends with",
    # Date Filter
    "dateFormatOoo": "yyyy-mm-dd",
    "before": "Before",
    "after": "After",
    # Filter Conditions
    "andCondition": "AND",
    "orCondition": "OR",
    # Filter Buttons
    "applyFilter": "Apply",
    "resetFilter": "Reset",
    "clearFilter": "Clear",
    "cancelFilter": "Cancel",
    # Filter Titles
    "textFilter": "Text Filter",
    "numberFilter": "Number Filter",
    "dateFilter": "Date Filter",
    "setFilter": "Set Filter",
    # Group Column Filter
    "groupFilterSelect": "Select field:",
    # Advanced Filter
    "advancedFilterContains": "contains",
    "advancedFilterNotContains": "does not contain",
    "advancedFilterTextEquals": "equals",
    "advancedFilterTextNotEqual": "does not equal",
    "advancedFilterStartsWith": "begins with",
    "advancedFilterEndsWith": "ends with",
    "advancedFilterBlank": "is blank",
    "advancedFilterNotBlank": "is not blank",
    "advancedFilterEquals": "=",
    "advancedFilterNotEqual": "!=",
    "advancedFilterGreaterThan": ">",
    "advancedFilterGreaterThanOrEqual": ">=",
    "advancedFilterLessThan": "<",
    "advancedFilterLessThanOrEqual": "<=",
    "advancedFilterTrue": "is true",
    "advancedFilterFalse": "is false",
    "advancedFilterAnd": "AND",
    "advancedFilterOr": "OR",
    "advancedFilterApply": "Apply",
    "advancedFilterBuilder": "Builder",
    "advancedFilterValidationMissingColumn": "Column is missing",
    "advancedFilterValidationMissingOption": "Option is missing",
    "advancedFilterValidationMissingValue": "Value is missing",
    "advancedFilterValidationInvalidColumn": "Column not found",
    "advancedFilterValidationInvalidOption": "Option not found",
    "advancedFilterValidationMissingQuote": "Value is missing an end quote",
    "advancedFilterValidationNotANumber": "Value is not a number",
    "advancedFilterValidationInvalidDate": "Value is not a valid date",
    "advancedFilterValidationMissingCondition": "Condition is missing",
    "advancedFilterValidationJoinOperatorMismatch": "Join operators within a condition must be the same",
    "advancedFilterValidationInvalidJoinOperator": "Join operator not found",
    "advancedFilterValidationMissingEndBracket": "Missing end bracket",
    "advancedFilterValidationExtraEndBracket": "Too many end brackets",
    "advancedFilterValidationMessage": "Expression has an error. ${variable} - ${variable}.",
    "advancedFilterValidationMessageAtEnd": "Expression has an error. ${variable} at end of expression.",
    "advancedFilterBuilderTitle": "Advanced Filter",
    "advancedFilterBuilderApply": "Apply",
    "advancedFilterBuilderCancel": "Cancel",
    "advancedFilterBuilderAddButtonTooltip": "Add Filter or Group",
    "advancedFilterBuilderRemoveButtonTooltip": "Remove",
    "advancedFilterBuilderMoveUpButtonTooltip": "Move Up",
    "advancedFilterBuilderMoveDownButtonTooltip": "Move Down",
    "advancedFilterBuilderAddJoin": "Add Group",
    "advancedFilterBuilderAddCondition": "Add Filter",
    "advancedFilterBuilderSelectColumn": "Select a column",
    "advancedFilterBuilderSelectOption": "Select an option",
    "advancedFilterBuilderEnterValue": "Enter a value...",
    "advancedFilterBuilderValidationAlreadyApplied": "Current filter already applied.",
    "advancedFilterBuilderValidationIncomplete": "Not all conditions are complete.",
    "advancedFilterBuilderValidationSelectColumn": "Must select a column.",
    "advancedFilterBuilderValidationSelectOption": "Must select an option.",
    "advancedFilterBuilderValidationEnterValue": "Must enter a value.",
    # Side Bar
    "columns": "Columns",
    "filters": "Filters",
    # columns tool panel
    "pivotMode": "Pivot Mode",
    "groups": "Row Groups",
    "rowGroupColumnsEmptyMessage": "Drag here to set row groups",
    "values": "Values",
    "valueColumnsEmptyMessage": "Drag here to aggregate",
    "pivots": "Column Labels",
    "pivotColumnsEmptyMessage": "Drag here to set column labels",
    # Header of the Default Group Column
    "group": "Group",
    # Row Drag
    "rowDragRow": "row",
    "rowDragRows": "rows",
    # Other
    "loadingOoo": "Loading...",
    "loadingError": "ERR",
    "noRowsToShow": "No Rows To Show",
    "enabled": "Enabled",
    # Menu
    "pinColumn": "Pin Column",
    "pinLeft": "Pin Left",
    "pinRight": "Pin Right",
    "noPin": "No Pin",
    "valueAggregation": "Value Aggregation",
    "noAggregation": "None",
    "autosizeThiscolumn": "Autosize This Column",
    "autosizeAllColumns": "Autosize All Columns",
    "groupBy": "Group by",
    "ungroupBy": "Un-Group by",
    "ungroupAll": "Un-Group All",
    "addToValues": "Add ${variable} to values",
    "removeFromValues": "Remove ${variable} from values",
    "addToLabels": "Add ${variable} to labels",
    "removeFromLabels": "Remove ${variable} from labels",
    "resetColumns": "Reset Columns",
    "expandAll": "Expand All Row Groups",
    "collapseAll": "Close All Row Groups",
    "ctrlC": "Ctrl+C",
    "ctrlX": "Ctrl+X",
    "copyWithHeaders": "Copy With Headers",
    "copyWithGroupHeaders": "Copy with Group Headers",
    "cut": "Cut",
    "paste": "Paste",
    "ctrlV": "Ctrl+V",
    "export": "Export",
    "csvExport": "CSV Export",
    "excelExport": "Excel Export",
    "columnFilter": "Column Filter",
    "columnChooser": "Choose Columns",
    "sortAscending": "Sort Ascending",
    "sortDescending": "Sort Descending",
    "sortUnSort": "Clear Sort",
    # Enterprise Menu Aggregation and Status Bar
    "sum": "Sum",
    "first": "First",
    "last": "Last",
    "min": "Min",
    "max": "Max",
    "none": "None",
    "count": "Count",
    "avg": "Average",
    "filteredRows": "Filtered",
    "selectedRows": "Selected",
    "totalRows": "Total Rows",
    "totalAndFilteredRows": "Rows",
    "more": "More",
    "to": "to",
    "of": "of",
    "page": "Page",
    "pageLastRowUnknown": "?",
    "nextPage": "Next Page",
    "lastPage": "Last Page",
    "firstPage": "First Page",
    "previousPage": "Previous Page",
    "pageSizeSelectorLabel": "Page Size:",
    "footerTotal": "Total",
    # Pivoting
    "pivotColumnGroupTotals": "Total",
    # Enterprise Menu (Charts)
    "pivotChartAndPivotMode": "Pivot Chart & Pivot Mode",
    "pivotChart": "Pivot Chart",
    "chartRange": "Chart Range",
    "columnChart": "Column",
    "groupedColumn": "Grouped",
    "stackedColumn": "Stacked",
    "normalizedColumn": "100% Stacked",
    "barChart": "Bar",
    "groupedBar": "Grouped",
    "stackedBar": "Stacked",
    "normalizedBar": "100% Stacked",
    "pieChart": "Pie",
    "pie": "Pie",
    "donut": "Donut",
    "line": "Line",
    "xyChart": "X Y (Scatter)",
    "scatter": "Scatter",
    "bubble": "Bubble",
    "areaChart": "Area",
    "area": "Area",
    "stackedArea": "Stacked",
    "normalizedArea": "100% Stacked",
    "histogramChart": "Histogram",
    "histogramFrequency": "Frequency",
    "polarChart": "Polar",
    "radarLine": "Radar Line",
    "radarArea": "Radar Area",
    "nightingale": "Nightingale",
    "radialColumn": "Radial Column",
    "radialBar": "Radial Bar",
    "statisticalChart": "Statistical",
    "boxPlot": "Box Plot",
    "rangeBar": "Range Bar",
    "rangeArea": "Range Area",
    "hierarchicalChart": "Hierarchical",
    "treemap": "Treemap",
    "sunburst": "Sunburst",
    "specializedChart": "Specialized",
    "waterfall": "Waterfall",
    "heatmap": "Heatmap",
    "combinationChart": "Combination",
    "columnLineCombo": "Column & Line",
    "AreaColumnCombo": "Area & Column",
    # Charts
    "pivotChartTitle": "Pivot Chart",
    "rangeChartTitle": "Range Chart",
    "settings": "Chart",
    "data": "Data",
    "format": "Format",
    "categories": "Categories",
    "defaultCategory": "(None)",
    "series": "Series",
    "switchCategorySeries": "Switch Category / Series",
    "categoryValues": "Category Values",
    "seriesLabels": "Series Labels",
    "aggregate": "Aggregate",
    "xyValues": "X Y Values",
    "paired": "Paired Mode",
    "axis": "Axis",
    "xAxis": "Horizontal Axis",
    "yAxis": "Vertical Axis",
    "polarAxis": "Polar Axis",
    "radiusAxis": "Radius Axis",
    "navigator": "Navigator",
    "zoom": "Zoom",
    "animation": "Animation",
    "crosshair": "Crosshair",
    "color": "Color",
    "thickness": "Thickness",
    "preferredLength": "Preferred Length",
    "xType": "X Type",
    "axisType": "Axis Type",
    "automatic": "Automatic",
    "category": "Category",
    "number": "Number",
    "time": "Time",
    "timeFormat": "Time Format",
    "autoRotate": "Auto Rotate",
    "labelRotation": "Rotation",
    "circle": "Circle",
    "polygon": "Polygon",
    "orientation": "Orientation",
    "fixed": "Fixed",
    "parallel": "Parallel",
    "perpendicular": "Perpendicular",
    "radiusAxisPosition": "Position",
    "ticks": "Ticks",
    "gridLines": "Grid Lines",
    "width": "Width",
    "height": "Height",
    "length": "Length",
    "padding": "Padding",
    "spacing": "Spacing",
    "chart": "Chart",
    "title": "Title",
    "titlePlaceholder": "Chart title - double click to edit",
    "background": "Background",
    "font": "Font",
    "top": "Top",
    "right": "Right",
    "bottom": "Bottom",
    "left": "Left",
    "labels": "Labels",
    "calloutLabels": "Callout Labels",
    "sectorLabels": "Sector Labels",
    "positionRatio": "Position Ratio",
    "size": "Size",
    "shape": "Shape",
    "minSize": "Minimum Size",
    "maxSize": "Maximum Size",
    "legend": "Legend",
    "position": "Position",
    "markerSize": "Marker Size",
    "markerStroke": "Marker Stroke",
    "markerPadding": "Marker Padding",
    "itemSpacing": "Item Spacing",
    "itemPaddingX": "Item Padding X",
    "itemPaddingY": "Item Padding Y",
    "layoutHorizontalSpacing": "Horizontal Spacing",
    "layoutVerticalSpacing": "Vertical Spacing",
    "strokeWidth": "Stroke Width",
    "offset": "Offset",
    "offsets": "Offsets",
    "tooltips": "Tooltips",
    "callout": "Callout",
    "markers": "Markers",
    "shadow": "Shadow",
    "blur": "Blur",
    "xOffset": "X Offset",
    "yOffset": "Y Offset",
    "lineWidth": "Line Width",
    "lineDash": "Line Dash",
    "lineDashOffset": "Dash Offset",
    "scrollingZoom": "Scrolling",
    "scrollingStep": "Scrolling Step",
    "selectingZoom": "Selecting",
    "durationMillis": "Duration (ms)",
    "crosshairLabel": "Label",
    "crosshairSnap": "Snap to Node",
    "normal": "Normal",
    "bold": "Bold",
    "italic": "Italic",
    "boldItalic": "Bold Italic",
    "predefined": "Predefined",
    "fillOpacity": "Fill Opacity",
    "strokeColor": "Line Color",
    "strokeOpacity": "Line Opacity",
    "miniChart": "Mini-Chart",
    "histogramBinCount": "Bin count",
    "connectorLine": "Connector Line",
    "seriesItems": "Series Items",
    "seriesItemType": "Item Type",
    "seriesItemPositive": "Positive",
    "seriesItemNegative": "Negative",
    "seriesItemLabels": "Item Labels",
    "columnGroup": "Column",
    "barGroup": "Bar",
    "pieGroup": "Pie",
    "lineGroup": "Line",
    "scatterGroup": "X Y (Scatter)",
    "areaGroup": "Area",
    "polarGroup": "Polar",
    "statisticalGroup": "Statistical",
    "hierarchicalGroup": "Hierarchical",
    "specializedGroup": "Specialized",
    "combinationGroup": "Combination",
    "groupedColumnTooltip": "Grouped",
    "stackedColumnTooltip": "Stacked",
    "normalizedColumnTooltip": "100% Stacked",
    "groupedBarTooltip": "Grouped",
    "stackedBarTooltip": "Stacked",
    "normalizedBarTooltip": "100% Stacked",
    "pieTooltip": "Pie",
    "donutTooltip": "Donut",
    "lineTooltip": "Line",
    "groupedAreaTooltip": "Area",
    "stackedAreaTooltip": "Stacked",
    "normalizedAreaTooltip": "100% Stacked",
    "scatterTooltip": "Scatter",
    "bubbleTooltip": "Bubble",
    "histogramTooltip": "Histogram",
    "radialColumnTooltip": "Radial Column",
    "radialBarTooltip": "Radial Bar",
    "radarLineTooltip": "Radar Line",
    "radarAreaTooltip": "Radar Area",
    "nightingaleTooltip": "Nightingale",
    "rangeBarTooltip": "Range Bar",
    "rangeAreaTooltip": "Range Area",
    "boxPlotTooltip": "Box Plot",
    "treemapTooltip": "Treemap",
    "sunburstTooltip": "Sunburst",
    "waterfallTooltip": "Waterfall",
    "heatmapTooltip": "Heatmap",
    "columnLineComboTooltip": "Column & Line",
    "areaColumnComboTooltip": "Area & Column",
    "customComboTooltip": "Custom Combination",
    "innerRadius": "Inner Radius",
    "startAngle": "Start Angle",
    "endAngle": "End Angle",
    "reverseDirection": "Reverse Direction",
    "groupPadding": "Group Padding",
    "seriesPadding": "Series Padding",
    "tile": "Tile",
    "whisker": "Whisker",
    "cap": "Cap",
    "capLengthRatio": "Length Ratio",
    "labelPlacement": "Placement",
    "inside": "Inside",
    "outside": "Outside",
    "noDataToChart": "No data available to be charted.",
    "pivotChartRequiresPivotMode": "Pivot Chart requires Pivot Mode enabled.",
    "chartSettingsToolbarTooltip": "Menu",
    "chartLinkToolbarTooltip": "Linked to Grid",
    "chartUnlinkToolbarTooltip": "Unlinked from Grid",
    "chartDownloadToolbarTooltip": "Download Chart",
    "chartEdit": "Edit Chart",
    "chartAdvancedSettings": "Advanced Settings",
    "chartLink": "Link to Grid",
    "chartUnlink": "Unlink from Grid",
    "chartDownload": "Download Chart",
    "seriesChartType": "Series Chart Type",
    "seriesType": "Series Type",
    "secondaryAxis": "Secondary Axis",
    "seriesAdd": "Add a series",
    "categoryAdd": "Add a category",
    "advancedSettings": "Advanced Settings",
    "direction": "Direction",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "seriesGroupType": "Group Type",
    "groupedSeriesGroupType": "Grouped",
    "stackedSeriesGroupType": "Stacked",
    "normalizedSeriesGroupType": "100% Stacked",
    # ARIA
    "ariaAdvancedFilterBuilderItem": "${variable}. Level ${variable}. Press ENTER to edit.",
    "ariaAdvancedFilterBuilderItemValidation": "${variable}. Level ${variable}. ${variable} Press ENTER to edit.",
    "ariaAdvancedFilterBuilderList": "Advanced Filter Builder List",
    "ariaAdvancedFilterBuilderFilterItem": "Filter Condition",
    "ariaAdvancedFilterBuilderGroupItem": "Filter Group",
    "ariaAdvancedFilterBuilderColumn": "Column",
    "ariaAdvancedFilterBuilderOption": "Option",
    "ariaAdvancedFilterBuilderValueP": "Value",
    "ariaAdvancedFilterBuilderJoinOperator": "Join Operator",
    "ariaAdvancedFilterInput": "Advanced Filter Input",
    "ariaChecked": "checked",
    "ariaColumn": "Column",
    "ariaColumnGroup": "Column Group",
    "ariaColumnFiltered": "Column Filtered",
    "ariaColumnSelectAll": "Toggle Select All Columns",
    "ariaDateFilterInput": "Date Filter Input",
    "ariaDefaultListName": "List",
    "ariaFilterColumnsInput": "Filter Columns Input",
    "ariaFilterFromValue": "Filter from value",
    "ariaFilterInput": "Filter Input",
    "ariaFilterList": "Filter List",
    "ariaFilterToValue": "Filter to value",
    "ariaFilterValue": "Filter Value",
    "ariaFilterMenuOpen": "Open Filter Menu",
    "ariaFilteringOperator": "Filtering Operator",
    "ariaHidden": "hidden",
    "ariaIndeterminate": "indeterminate",
    "ariaInputEditor": "Input Editor",
    "ariaMenuColumn": "Press ALT DOWN to open column menu",
    "ariaFilterColumn": "Press CTRL ENTER to open filter",
    "ariaRowDeselect": "Press SPACE to deselect this row",
    "ariaRowSelectAll": "Press Space to toggle all rows selection",
    "ariaRowToggleSelection": "Press Space to toggle row selection",
    "ariaRowSelect": "Press SPACE to select this row",
    "ariaRowSelectionDisabled": "Row Selection is disabled for this row",
    "ariaSearch": "Search",
    "ariaSortableColumn": "Press ENTER to sort",
    "ariaToggleVisibility": "Press SPACE to toggle visibility",
    "ariaToggleCellValue": "Press SPACE to toggle cell value",
    "ariaUnchecked": "unchecked",
    "ariaVisible": "visible",
    "ariaSearchFilterValues": "Search filter values",
    "ariaPageSizeSelectorLabel": "Page Size",
    "ariaChartMenuClose": "Close Chart Edit Menu",
    "ariaSkeletonCellLoadingFailed": "Row failed to load",
    "ariaSkeletonCellLoading": "Row data is loading",
    # ARIA Labels for Drop Zones
    "ariaRowGroupDropZonePanelLabel": "Row Groups",
    "ariaValuesDropZonePanelLabel": "Values",
    "ariaPivotDropZonePanelLabel": "Column Labels",
    "ariaDropZoneColumnComponentDescription": "Press DELETE to remove",
    "ariaDropZoneColumnValueItemDescription": "Press ENTER to change the aggregation type",
    "ariaDropZoneColumnGroupItemDescription": "Press ENTER to sort",
    # used for aggregate drop zone, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeparator}{column name}
    "ariaDropZoneColumnComponentAggFuncSeparator": " of ",
    "ariaDropZoneColumnComponentSortAscending": "ascending",
    "ariaDropZoneColumnComponentSortDescending": "descending",
    # ARIA Labels for Dialogs
    "ariaLabelColumnMenu": "Column Menu",
    "ariaLabelColumnFilter": "Column Filter",
    "ariaLabelCellEditor": "Cell Editor",
    "ariaLabelDialog": "Dialog",
    "ariaLabelSelectField": "Select Field",
    "ariaLabelRichSelectField": "Rich Select Field",
    "ariaLabelTooltip": "Tooltip",
    "ariaLabelContextMenu": "Context Menu",
    "ariaLabelSubMenu": "SubMenu",
    "ariaLabelAggregationFunction": "Aggregation Function",
    "ariaLabelAdvancedFilterAutocomplete": "Advanced Filter Autocomplete",
    "ariaLabelAdvancedFilterBuilderAddField": "Advanced Filter Builder Add Field",
    "ariaLabelAdvancedFilterBuilderColumnSelectField": "Advanced Filter Builder Column Select Field",
    "ariaLabelAdvancedFilterBuilderOptionSelectField": "Advanced Filter Builder Option Select Field",
    "ariaLabelAdvancedFilterBuilderJoinSelectField": "Advanced Filter Builder Join Operator Select Field",
    # ARIA Labels for the Side Bar
    "ariaColumnPanelList": "Column List",
    "ariaFilterPanelList": "Filter List",
    # Number Format (Status Bar, Pagination Panel)
    "thousandSeparator": ",",
    "decimalSeparator": ".",
    # Data types
    "true": "True",
    "false": "False",
    "invalidDate": "Invalid Date",
    "invalidNumber": "Invalid Number",
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December",
    # Time formats
    "timeFormatSlashesDDMMYYYY": "DD/MM/YYYY",
    "timeFormatSlashesMMDDYYYY": "MM/DD/YYYY",
    "timeFormatSlashesDDMMYY": "DD/MM/YY",
    "timeFormatSlashesMMDDYY": "MM/DD/YY",
    "timeFormatDotsDDMYY": "DD.M.YY",
    "timeFormatDotsMDDYY": "M.DD.YY",
    "timeFormatDashesYYYYMMDD": "YYYY-MM-DD",
    "timeFormatSpacesDDMMMMYYYY": "DD MMMM YYYY",
    "timeFormatHHMMSS": "HH:MM:SS",
    "timeFormatHHMMSSAmPm": "HH:MM:SS AM/PM",
}


# AG-GRID的中文语言包
AG_GRID_LOCALE_CN = {
    "selectAll": "（全选）",
    "selectAllSearchResults": "（选择所有搜索结果）",
    "addCurrentSelectionToFilter": "将目前选择添加到过滤器",
    "searchOoo": "搜索...",
    "blanks": "（空白）",
    "noMatches": "无匹配",
    "filterOoo": "筛选...",
    "equals": "等于",
    "notEqual": "不相等",
    "blank": "空白的",
    "notBlank": "不是空白",
    "empty": "选一个",
    "lessThan": "少于",
    "greaterThan": "比...更大",
    "lessThanOrEqual": "小于或等于",
    "greaterThanOrEqual": "大于或等于",
    "inRange": "之间",
    "inRangeStart": "从",
    "inRangeEnd": "到",
    "contains": "包含",
    "notContains": "不含",
    "startsWith": "开始于",
    "endsWith": "以..结束",
    "dateFormatOoo": "yyyy-mm-dd",
    "before": "前",
    "after": "后",
    "andCondition": "和",
    "orCondition": "或者",
    "applyFilter": "申请",
    "resetFilter": "重置",
    "clearFilter": "清除",
    "cancelFilter": "取消",
    "textFilter": "文本过滤器",
    "numberFilter": "数字过滤器",
    "dateFilter": "日期过滤器",
    "setFilter": "设置过滤器",
    "groupFilterSelect": "选择字段:",
    "advancedFilterContains": "包含",
    "advancedFilterNotContains": "不含",
    "advancedFilterTextEquals": "等于",
    "advancedFilterTextNotEqual": "不相等",
    "advancedFilterStartsWith": "开始于",
    "advancedFilterEndsWith": "以..结束",
    "advancedFilterBlank": "是空白的",
    "advancedFilterNotBlank": "不是空白",
    "advancedFilterEquals": "=",
    "advancedFilterNotEqual": "!=",
    "advancedFilterGreaterThan": ">",
    "advancedFilterGreaterThanOrEqual": ">=",
    "advancedFilterLessThan": "<",
    "advancedFilterLessThanOrEqual": "<=",
    "advancedFilterTrue": "是真的",
    "advancedFilterFalse": "是错误的",
    "advancedFilterAnd": "和",
    "advancedFilterOr": "或者",
    "advancedFilterApply": "申请",
    "advancedFilterBuilder": "建筑商",
    "advancedFilterValidationMissingColumn": "列缺少",
    "advancedFilterValidationMissingOption": "选项丢失",
    "advancedFilterValidationMissingValue": "值丢失",
    "advancedFilterValidationInvalidColumn": "找不到列",
    "advancedFilterValidationInvalidOption": "找不到选项",
    "advancedFilterValidationMissingQuote": "价值缺少结尾报价",
    "advancedFilterValidationNotANumber": "价值不是数字",
    "advancedFilterValidationInvalidDate": "价值不是有效的日期",
    "advancedFilterValidationMissingCondition": "条件缺失",
    "advancedFilterValidationJoinOperatorMismatch": "在条件下加入操作员必须相同",
    "advancedFilterValidationInvalidJoinOperator": "加入未找到的操作员",
    "advancedFilterValidationMissingEndBracket": "缺少结束括号",
    "advancedFilterValidationExtraEndBracket": "结束括号太多",
    "advancedFilterValidationMessage": "表达有错误.${variable}-${variable}.",
    "advancedFilterValidationMessageAtEnd": "表达有错误.${variable}在表达式结束时.",
    "advancedFilterBuilderTitle": "高级过滤器",
    "advancedFilterBuilderApply": "申请",
    "advancedFilterBuilderCancel": "取消",
    "advancedFilterBuilderAddButtonTooltip": "添加过滤器或组",
    "advancedFilterBuilderRemoveButtonTooltip": "消除",
    "advancedFilterBuilderMoveUpButtonTooltip": "提升",
    "advancedFilterBuilderMoveDownButtonTooltip": "向下移动",
    "advancedFilterBuilderAddJoin": "添加组",
    "advancedFilterBuilderAddCondition": "添加过滤器",
    "advancedFilterBuilderSelectColumn": "选择一列",
    "advancedFilterBuilderSelectOption": "选择一个选项",
    "advancedFilterBuilderEnterValue": "输入一个值...",
    "advancedFilterBuilderValidationAlreadyApplied": "当前的过滤器已经应用.",
    "advancedFilterBuilderValidationIncomplete": "并非所有条件都完成.",
    "advancedFilterBuilderValidationSelectColumn": "必须选择一列.",
    "advancedFilterBuilderValidationSelectOption": "必须选择一个选项.",
    "advancedFilterBuilderValidationEnterValue": "必须输入一个值.",
    "columns": "列",
    "filters": "过滤器",
    "pivotMode": "枢轴模式",
    "groups": "行组",
    "rowGroupColumnsEmptyMessage": "在这里拖动以设置行组",
    "values": "值",
    "valueColumnsEmptyMessage": "在这里拖动以汇总",
    "pivots": "列标签",
    "pivotColumnsEmptyMessage": "在这里拖动设置列标签",
    "group": "团体",
    "rowDragRow": "排",
    "rowDragRows": "行",
    "loadingOoo": "加载中...",
    "loadingError": "呃",
    "noRowsToShow": "没有行显示",
    "enabled": "启用",
    #"pinColumn": "引脚柱",
    #"pinLeft": "小别针",
    #"pinRight": "销钉正确",
    #"noPin": "没有别针",
    "valueAggregation": "值聚合",
    "noAggregation": "不聚合",
    "autosizeThiscolumn": "自动此列尺寸",
    "autosizeAllColumns": "自动所有列尺寸",
    "groupBy": "通过...分组",
    "ungroupBy": "不组",
    "ungroupAll": "不组",
    "addToValues": "将${variable}添加到值",
    "removeFromValues": "从值中删除${variable}",
    "addToLabels": "将${variable}添加到标签",
    "removeFromLabels": "从标签中删除${variable}",
    "resetColumns": "重置列",
    "expandAll": "扩展所有行组",
    "collapseAll": "关闭所有行组",
    "ctrlC": "Ctrl+c",
    "ctrlX": "Ctrl+X",
    "copyWithHeaders": "用标题复制",
    "copyWithGroupHeaders": "用小组标题复制",
    "copy": "复制",
    "cut": "剪切",
    "paste": "粘贴",
    "ctrlV": "Ctrl+V.",
    "export": "导出",
    "csvExport": "CSV导出",
    "excelExport": "Excel导出",
    "columnFilter": "列过滤器",
    "columnChooser": "选择列",
    "sortAscending": "升序",
    "sortDescending": "排序下降",
    "sortUnSort": "清除排序",
    "sum": "和",
    "first": "第一的",
    "last": "最后的",
    "min": "最小",
    "max": "最大限度",
    "none": "没有任何",
    "count": "数数",
    "avg": "平均的",
    "filteredRows": "过滤",
    "selectedRows": "选定",
    "totalRows": "总行",
    "totalAndFilteredRows": "行",
    "more": "更多的",
    "to": "到",
    "of": "的",
    "page": "页",
    "pageLastRowUnknown": "?",
    "nextPage": "下一页",
    "lastPage": "最后一页",
    "firstPage": "第一页",
    "previousPage": "上一页",
    "pageSizeSelectorLabel": "页面大小:",
    "footerTotal": "全部的",
    "pivotColumnGroupTotals": "全部的",
    "pivotChartAndPivotMode": "枢轴图和枢轴模式",
    "pivotChart": "枢轴图",
    "chartRange": "图表范围",
    "columnChart": "柱子",
    "groupedColumn": "分组",
    "stackedColumn": "堆叠",
    "normalizedColumn": "100％堆叠",
    "barChart": "酒吧",
    "groupedBar": "分组",
    "stackedBar": "堆叠",
    "normalizedBar": "100％堆叠",
    "pieChart": "馅饼",
    "pie": "馅饼",
    "donut": "油炸圈饼",
    "line": "线",
    "xyChart": "x y（散射）",
    "scatter": "分散",
    "bubble": "气泡",
    "areaChart": "区域",
    "area": "区域",
    "stackedArea": "堆叠",
    "normalizedArea": "100％堆叠",
    "histogramChart": "直方图",
    "histogramFrequency": "频率",
    "polarChart": "极性",
    "radarLine": "雷达线",
    "radarArea": "雷达区域",
    "nightingale": "夜莺",
    "radialColumn": "径向柱",
    "radialBar": "径向条",
    "statisticalChart": "统计",
    "boxPlot": "箱形图",
    "rangeBar": "范围栏",
    "rangeArea": "范围区域",
    "hierarchicalChart": "分层",
    "treemap": "Treemap",
    "sunburst": "朝阳",
    "specializedChart": "专门",
    "waterfall": "瀑布",
    "heatmap": "热图",
    "combinationChart": "组合",
    "columnLineCombo": "列和线",
    "AreaColumnCombo": "区域和柱",
    "pivotChartTitle": "枢轴图",
    "rangeChartTitle": "范围图",
    "settings": "图表",
    "data": "数据",
    "format": "格式",
    "categories": "类别",
    "defaultCategory": "（没有任何）",
    "series": "系列",
    "switchCategorySeries": "开关类别/系列",
    "categoryValues": "类别值",
    "seriesLabels": "系列标签",
    "aggregate": "总计的",
    "xyValues": "x y值",
    "paired": "配对模式",
    "axis": "轴",
    "xAxis": "横轴",
    "yAxis": "垂直轴",
    "polarAxis": "极轴",
    "radiusAxis": "半径轴",
    "navigator": "航海家",
    "zoom": "飞涨",
    "animation": "动画片",
    "crosshair": "十字路口",
    "color": "颜色",
    "thickness": "厚度",
    "preferredLength": "首选长度",
    "xType": "X类型",
    "axisType": "轴类型",
    "automatic": "自动的",
    "category": "类别",
    "number": "数字",
    "time": "时间",
    "timeFormat": "时间格式",
    "autoRotate": "自动旋转",
    "labelRotation": "回转",
    "circle": "圆圈",
    "polygon": "多边形",
    "orientation": "方向",
    "fixed": "固定的",
    "parallel": "平行线",
    "perpendicular": "垂直",
    "radiusAxisPosition": "位置",
    "ticks": "tick",
    "gridLines": "网格线",
    "width": "宽度",
    "height": "高度",
    "length": "长度",
    "padding": "填充",
    "spacing": "间距",
    "chart": "图表",
    "title": "标题",
    "titlePlaceholder": "图表标题 - 双击以编辑",
    "background": "背景",
    "font": "字体",
    "top": "顶部",
    "right": "正确的",
    "bottom": "底部",
    "left": "左边",
    "labels": "标签",
    "calloutLabels": "标签",
    "sectorLabels": "部门标签",
    "positionRatio": "位置比",
    "size": "尺寸",
    "shape": "形状",
    "minSize": "最小尺寸",
    "maxSize": "最大尺寸",
    "legend": "传奇",
    "position": "位置",
    "markerSize": "标记大小",
    "markerStroke": "标记中风",
    "markerPadding": "标记填充",
    "itemSpacing": "项目间距",
    "itemPaddingX": "项目填充x",
    "itemPaddingY": "项目填充y",
    "layoutHorizontalSpacing": "水平间距",
    "layoutVerticalSpacing": "垂直间距",
    "strokeWidth": "中风宽度",
    "offset": "抵消",
    "offsets": "偏移",
    "tooltips": "工具提示",
    "callout": "大喊",
    "markers": "标记",
    "shadow": "阴影",
    "blur": "模糊",
    "xOffset": "x偏移",
    "yOffset": "y偏移",
    "lineWidth": "行宽",
    "lineDash": "线破折号",
    "lineDashOffset": "破折号偏移",
    "scrollingZoom": "滚动",
    "scrollingStep": "滚动步骤",
    "selectingZoom": "选择",
    "durationMillis": "持续时间（MS）",
    "crosshairLabel": "标签",
    "crosshairSnap": "快点到节点",
    "normal": "普通的",
    "bold": "大胆的",
    "italic": "斜体",
    "boldItalic": "加粗斜体",
    "predefined": "预定义",
    "fillOpacity": "填充不透明度",
    "strokeColor": "线颜色",
    "strokeOpacity": "线不透明度",
    "miniChart": "迷你图",
    "histogramBinCount": "bin count",
    "connectorLine": "连接器线",
    "seriesItems": "系列项目",
    "seriesItemType": "物品种类",
    "seriesItemPositive": "积极的",
    "seriesItemNegative": "消极的",
    "seriesItemLabels": "项目标签",
    "columnGroup": "柱子",
    "barGroup": "酒吧",
    "pieGroup": "馅饼",
    "lineGroup": "线",
    "scatterGroup": "x y（散射）",
    "areaGroup": "区域",
    "polarGroup": "极性",
    "statisticalGroup": "统计",
    "hierarchicalGroup": "分层",
    "specializedGroup": "专门",
    "combinationGroup": "组合",
    "groupedColumnTooltip": "分组",
    "stackedColumnTooltip": "堆叠",
    "normalizedColumnTooltip": "100％堆叠",
    "groupedBarTooltip": "分组",
    "stackedBarTooltip": "堆叠",
    "normalizedBarTooltip": "100％堆叠",
    "pieTooltip": "馅饼",
    "donutTooltip": "油炸圈饼",
    "lineTooltip": "线",
    "groupedAreaTooltip": "区域",
    "stackedAreaTooltip": "堆叠",
    "normalizedAreaTooltip": "100％堆叠",
    "scatterTooltip": "分散",
    "bubbleTooltip": "气泡",
    "histogramTooltip": "直方图",
    "radialColumnTooltip": "径向柱",
    "radialBarTooltip": "径向条",
    "radarLineTooltip": "雷达线",
    "radarAreaTooltip": "雷达区域",
    "nightingaleTooltip": "夜莺",
    "rangeBarTooltip": "范围栏",
    "rangeAreaTooltip": "范围区域",
    "boxPlotTooltip": "箱形图",
    "treemapTooltip": "Treemap",
    "sunburstTooltip": "朝阳",
    "waterfallTooltip": "瀑布",
    "heatmapTooltip": "热图",
    "columnLineComboTooltip": "列和线",
    "areaColumnComboTooltip": "区域和柱",
    "customComboTooltip": "定制组合",
    "innerRadius": "内半径",
    "startAngle": "开始角度",
    "endAngle": "端角",
    "reverseDirection": "反向方向",
    "groupPadding": "小组填充",
    "seriesPadding": "系列填充",
    "tile": "瓦",
    "whisker": "晶须",
    "cap": "帽",
    "capLengthRatio": "长度比",
    "labelPlacement": "放置",
    "inside": "里面",
    "outside": "外部",
    "noDataToChart": "无需绘制数据.",
    "pivotChartRequiresPivotMode": "枢轴图需要启用枢轴模式.",
    "chartSettingsToolbarTooltip": "菜单",
    "chartLinkToolbarTooltip": "链接到网格",
    "chartUnlinkToolbarTooltip": "从网格上链接",
    "chartDownloadToolbarTooltip": "下载图表",
    "chartEdit": "编辑图表",
    "chartAdvancedSettings": "高级设置",
    "chartLink": "链接到网格",
    "chartUnlink": "从网格中链接",
    "chartDownload": "下载图表",
    "seriesChartType": "串联图表类型",
    "seriesType": "系列类型",
    "secondaryAxis": "次级轴",
    "seriesAdd": "添加系列",
    "categoryAdd": "添加类别",
    "advancedSettings": "高级设置",
    "direction": "方向",
    "horizontal": "水平的",
    "vertical": "垂直的",
    "seriesGroupType": "组类型",
    "groupedSeriesGroupType": "分组",
    "stackedSeriesGroupType": "堆叠",
    "normalizedSeriesGroupType": "100％堆叠",
    "ariaAdvancedFilterBuilderItem": "${variable}.级别${variable}.按Enter进行编辑.",
    "ariaAdvancedFilterBuilderItemValidation": "${variable}.级别${variable}.${variable}按Enter进行编辑.",
    "ariaAdvancedFilterBuilderList": "高级过滤器构建器列表",
    "ariaAdvancedFilterBuilderFilterItem": "过滤条件",
    "ariaAdvancedFilterBuilderGroupItem": "过滤器组",
    "ariaAdvancedFilterBuilderColumn": "柱子",
    "ariaAdvancedFilterBuilderOption": "选项",
    "ariaAdvancedFilterBuilderValueP": "价值",
    "ariaAdvancedFilterBuilderJoinOperator": "加入操作员",
    "ariaAdvancedFilterInput": "高级过滤器输入",
    "ariaChecked": "检查",
    "ariaColumn": "柱子",
    "ariaColumnGroup": "列组",
    "ariaColumnFiltered": "列过滤",
    "ariaColumnSelectAll": "切换选择所有列",
    "ariaDateFilterInput": "日期过滤器输入",
    "ariaDefaultListName": "列表",
    "ariaFilterColumnsInput": "过滤列输入",
    "ariaFilterFromValue": "从价值过滤",
    "ariaFilterInput": "过滤器输入",
    "ariaFilterList": "过滤器列表",
    "ariaFilterToValue": "过滤到值",
    "ariaFilterValue": "滤波器值",
    "ariaFilterMenuOpen": "打开过滤菜单",
    "ariaFilteringOperator": "过滤操作员",
    "ariaHidden": "隐",
    "ariaIndeterminate": "不定",
    "ariaInputEditor": "输入编辑器",
    "ariaMenuColumn": "按下alt down to打开列菜单",
    "ariaFilterColumn": "按CTRL输入以打开过滤器",
    "ariaRowDeselect": "按空格取消选择这一行",
    "ariaRowSelectAll": "按空格切换所有行选择",
    "ariaRowToggleSelection": "按空格切换行选择",
    "ariaRowSelect": "按空格选择此行",
    "ariaRowSelectionDisabled": "该行禁用行选择",
    "ariaSearch": "搜索",
    "ariaSortableColumn": "按Enter进行排序",
    "ariaToggleVisibility": "按空格切换可见性",
    "ariaToggleCellValue": "按空格切换单元格值",
    "ariaUnchecked": "未选中",
    "ariaVisible": "可见的",
    "ariaSearchFilterValues": "搜索过滤器值",
    "ariaPageSizeSelectorLabel": "页面大小",
    "ariaChartMenuClose": "关闭图表编辑菜单",
    "ariaSkeletonCellLoadingFailed": "行无法加载",
    "ariaSkeletonCellLoading": "行数据正在加载",
    "ariaRowGroupDropZonePanelLabel": "行组",
    "ariaValuesDropZonePanelLabel": "值",
    "ariaPivotDropZonePanelLabel": "列标签",
    "ariaDropZoneColumnComponentDescription": "按DELETE删除",
    "ariaDropZoneColumnValueItemDescription": "按Enter更改聚合类型",
    "ariaDropZoneColumnGroupItemDescription": "按Enter进行排序",
    "ariaDropZoneColumnComponentAggFuncSeparator": "的",
    "ariaDropZoneColumnComponentSortAscending": "上升",
    "ariaDropZoneColumnComponentSortDescending": "下降",
    "ariaLabelColumnMenu": "列菜单",
    "ariaLabelColumnFilter": "列过滤器",
    "ariaLabelCellEditor": "细胞编辑器",
    "ariaLabelDialog": "对话",
    "ariaLabelSelectField": "选择字段",
    "ariaLabelRichSelectField": "丰富的选择字段",
    "ariaLabelTooltip": "工具提示",
    "ariaLabelContextMenu": "上下文菜单",
    "ariaLabelSubMenu": "子菜单",
    "ariaLabelAggregationFunction": "聚合功能",
    "ariaLabelAdvancedFilterAutocomplete": "高级过滤器自动完成",
    "ariaLabelAdvancedFilterBuilderAddField": "高级过滤器构建器添加字段",
    "ariaLabelAdvancedFilterBuilderColumnSelectField": "高级过滤器构建器列选择字段",
    "ariaLabelAdvancedFilterBuilderOptionSelectField": "高级过滤器构建器选项选择字段",
    "ariaLabelAdvancedFilterBuilderJoinSelectField": "高级过滤器构建器加入操作员选择字段",
    "ariaColumnPanelList": "列列表",
    "ariaFilterPanelList": "过滤器列表",
    "thousandSeparator": ",,,,",
    "decimalSeparator": ".",
    "true": "真的",
    "false": "错误的",
    "invalidDate": "失效日期",
    "invalidNumber": "无效号码",
    "january": "一月",
    "february": "二月",
    "march": "行进",
    "april": "四月",
    "may": "可能",
    "june": "六月",
    "july": "七月",
    "august": "八月",
    "september": "九月",
    "october": "十月",
    "november": "十一月",
    "december": "十二月",
    "timeFormatSlashesDDMMYYYY": "dd/mm/yyyy",
    "timeFormatSlashesMMDDYYYY": "mm/dd/yyyy",
    "timeFormatSlashesDDMMYY": "dd/mm/yy",
    "timeFormatSlashesMMDDYY": "mm/dd/yy",
    "timeFormatDotsDDMYY": "DD.M.Yy",
    "timeFormatDotsMDDYY": "m.dd.yy",
    "timeFormatDashesYYYYMMDD": "yyyy-mm-dd",
    "timeFormatSpacesDDMMMMYYYY": "dd mmmm yyyy",
    "timeFormatHHMMSS": "HH:MM:SS",
    "timeFormatHHMMSSAmPm": "HH:MM:SS AM/PM",
}
